# Generated by Django 5.2.3 on 2025-08-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_invoice_created_at_remove_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rentalagreement',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='rental_days',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='item_type',
            field=models.CharField(choices=[('rental', 'Rental Charge'), ('late_fee', 'Late Fee'), ('damage', 'Damage Charge'), ('discount', 'Discount'), ('adjustment', 'Adjustment'), ('vat', 'VAT'), ('payment', 'Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.product'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
