# Generated by Django 5.2.3 on 2025-08-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='rental.product'),
        ),
    ]
