# Generated by Django 5.2.3 on 2025-08-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalitem',
            options={'ordering': ['rental__start_date']},
        ),
        migrations.RenameField(
            model_name='rentalitem',
            old_name='agreement',
            new_name='rental',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.product'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='return_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
