# Generated by Django 5.2.3 on 2025-08-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='rental.product'),
        ),
    ]
